apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: {{ .Chart.Name }}
spec:
  scheme: http
  loadbalancer:
    type: ewma
  discovery:
    type: dns
    serviceName: {{ .Chart.Name }}.{{ .Release.Namespace}}:{{ .Values.port }}
  timeout:
    connect: 6s
    send: 6s
    read: 6s
  passHost: pass
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ .Chart.Name }}
spec:
  http:
    - name: user-route
      match:
        methods:
          - GET
          - POST
          - DELETE
          - PUT
          - PATCH
          - OPTIONS
        paths:
          - /users
      upstreams:
        - name: {{ .Chart.Name }}
      plugins:
        - name: limit-count
          enable: true
          config:
            count: 2
            time_window: 60
            rejected_code: 503
            rejected_msg: "Requests are too many, please try again later or upgrade your subscription plan."
            key: "remote_addr"
        - name: basic-auth
          enable: true
          config:
            hide_credentials: true
---
apiVersion: apisix.apache.org/v2
kind: ApisixConsumer
metadata:
  name: {{ .Chart.Name }}
spec:
  authParameter:
    basicAuth:
      value:
        username: toto
        password: password