apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: {{ .Chart.Name }}
spec:
  scheme: http
  loadbalancer:
    type: ewma
  discovery:
    type: dns
    serviceName: {{ .Chart.Name }}.{{ .Release.Namespace}}:{{ .Values.port }}
  timeout:
    connect: 6s
    send: 6s
    read: 6s
  passHost: pass
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ .Chart.Name }}
spec:
  http:
    - name: company-route
      match:
        methods:
          - GET
          - POST
          - DELETE
          - PUT
          - PATCH
          - OPTIONS
        paths:
          - /companies/*
      upstreams:
        - name: {{ .Chart.Name }}
      plugin_config_name: {{ .Chart.Name }}
---
apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: {{ .Chart.Name }}
spec:
  plugins:
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri:
          - "/companies(/|$)(.*)"
          - "/$2"
