apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: app
        image: {{ .Values.werf.image.api_company }}
        command: {{ .Values.command }}
        {{ if .Values.port }}
        ports:
        - containerPort: {{ .Values.port }}
        {{ end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}