ingress:
  enabled: true
  className: private
  hosts:
    - host: apisix.placeholder.com
      paths:
        - /

metrics:
  serviceMonitor:
    enabled: true

apisix:
  discovery:
    enabled: true
    registry:
      kubernetes: {}
      dns:
        servers:
          - 10.40.0.10:53 # KubeDNS service IP address on staging

  nginx:
    envs:
      - KUBERNETES_SERVICE_HOST
      - KUBERNETES_SERVICE_PORT

rbac:
  create: true

dashboard:
  enabled: true
  ingress:
    enabled: true
    className: private
    hosts:
      - host: apisix-dashboard.placeholder.com
        paths:
          - /

# -- Ingress controller configuration
ingress-controller:
  enabled: true
  config:
    apisix:
      serviceNamespace: apisix # The namespace where the Apisix service is running
      clusterName: "default"
      adminAPIVersion: "v3"
